---

- name: Common Setup
  hosts: all
  remote_user: root
  roles:
    - common

- name: Web Setup
  hosts: webservers
  remote_user: root
  roles:
    - web

- name: DB Setup
  hosts: dbservers
  remote_user: root
  roles:
    - db
