---

- name: Install MariaDB
  apt:
    name: mariadb-server
    state: present

- name: Start MariaDB Service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Root MariaDB Configuration
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf
  notify:
    - restart mariadb

- name: Set Permission For Root MariaDB Configuration
  file:
    path: /root/.my.cnf
    owner: root
    group: root
    mode: '600'

- name: MariaDB Configuration
  template:
    src: mariadb.cnf.j2
    dest: /etc/mysql/mariadb.cnf
  notify:
    - restart mariadb

- name: Create Database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: Create Database User
  mysql_user:
    name: "{{ db_username }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: "%"
    state: present
    login_unix_socket: /var/run/mysqld/mysqld.sock
