---

- name: Install MySQL
  apt:
    name: mysql-server
    state: present

- name: Configure MySQL
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  notify:
    - restart mysql

- name: Start MySQL Service
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Create Database
  mysql_db:
    name: "{{ db_name }}"
    state: present

- name: Create Database User
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: "%"
    state: present
