---

- name: Add PHP PPA repository
  apt_repository:
    repo: ppa:ondrej/php
    state: present

- name: Install Dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php{{ php_version }}
    - php{{ php_version }}-fpm
    - php{{ php_version }}-bcmath
    - php{{ php_version }}-ctype
    - php{{ php_version }}-curl
    - php{{ php_version }}-dom
    - php{{ php_version }}-fileinfo
    - php{{ php_version }}-gd
    - php{{ php_version }}-iconv
    - php{{ php_version }}-intl
    - php{{ php_version }}-mbstring
    - php{{ php_version }}-mysql
    - php{{ php_version }}-simplexml
    - php{{ php_version }}-soap
    - php{{ php_version }}-sockets
    - php{{ php_version }}-tokenizer
    - php{{ php_version }}-xmlwriter
    - php{{ php_version }}-xsl
    - php{{ php_version }}-zip
