---

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy Nginx Configuration
  template:
    src: magento.conf.j2
    dest: /var/nginx/sites-available/magento.conf

- name: Enable Configuration
  file:
    src: /var/nginx/sites-available/magento.conf
    dest: /var/nginx/sites-enabled/magento.conf
    owner: www-data
    group: www-data
    state: link

- name: Start Nginx Service
  service:
    name: nginx
    state: started
    enabled: yes
